spring:
  cloud:
    config: 
      discovery:
        enabled: true
        service-id: config-server
      name: item-service
      profile: dev
      overide-none: true
  
eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
      
      
---
server:
  port: 8001
  

spring:  profiles:  - item1
  

---
server:  port: 8002
  
spring:  profiles:  - item2